# https://github.com/actions/labeler/blob/main/README.md

# When extending this, remember that in the PR, the labeler will run against
# the labeler.yml in main, more info:
# https://github.com/actions/labeler/issues/12
# This means your changes won't be tested. To test your branch, make a second
# branch with dummy changes, and open a PR on your own fork, against the
# first branch.


"doc-required":
- changed-files:
  - any-glob-to-any-file:
    - "doc/**/*"
    - "doc/*"
    - "**/*.rst"
    - "doc/**/*.txt"

"sid-tools":
- changed-files:
  - any-glob-to-any-file:
    - "tools/**/*"
    - "tools/*"

"sid-lib":
- changed-files:
  - any-glob-to-any-file:
    - "lib/**/*"
    - "lib/*"

"manifest":
- changed-files:
  - any-glob-to-any-file:
    - "west.yml"

"scripts":
- changed-files:
  - any-glob-to-any-file:
    - "scripts/**/*"
    - "scripts/*"

"tests":
- changed-files:
  - any-glob-to-any-file:
    - "tests/**/*"

# Add 'source' label to any change in repo EXCEPT the ones defined with ! at the beginning
"source":
- all:
  - changed-files:
    - any-glob-to-any-file: '**/*'
    - any-glob-to-all-files: ['!doc/**/*', '!doc/*', '!**/*.rst', '!doc/**/*.txt', '!tools/**/*', '!tools/*', '!lib/**/*', '!lib/*', '!west.yml', "!.devcontainer/*", "!scripts/*", "!scripts/**/*", "!tests/**/*", "!.github/*", "!.github/**/*"]
