# https://github.com/actions/labeler/blob/main/README.md

# When extending this, remember that in the PR, the labeler will run against
# the labeler.yml in main, more info:
# https://github.com/actions/labeler/issues/12
# This means your changes won't be tested. To test your branch, make a second
# branch with dummy changes, and open a PR on your own fork, against the
# first branch.


"doc-required":
  - "doc/**/*"
  - "**/*.rst"

"sid-tools":
  - "tools/**/*"

"sid-libs":
  - "lib/**/*"

"manifest":
  - "west.yml"

# Add 'source' label to any change in repo EXCEPT the ones defined with ! at the beginning
"source":
  - any: ['**/*', '!docs/**/*', '!**/*.rst', '!tools/**/*', '!lib/**/*', '!west.yml']
