# Copyright (c) 2026 Nordic Semiconductor ASA
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# Sidewalk is a downstream Zephyr module: relax checkpatch rules that are
# noisy for generated macros, long shell tables, DTS overlays, and Kconfig
# imported from application samples.
--ignore DOS_LINE_ENDINGS
--ignore SPDX_LICENSE_TAG
--ignore LONG_LINE
--ignore LONG_LINE_STRING
--ignore LONG_LINE_COMMENT
--ignore SPLIT_STRING
--ignore AVOID_EXTERNS
--ignore CONFIG_DESCRIPTION
--ignore LEADING_SPACE
--ignore LINE_SPACING
--ignore COMPLEX_MACRO
--ignore CONSTANT_COMPARISON
