# The west manifest file (west.yml) for Sidewalk in nRF Connect SDK (NCS).

manifest:
  defaults:
    remote: ncs

  remotes:
    # nRF Connect SDK base URL.
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: aws-samples
      url-base: https://github.com/aws-samples

  projects:
    - name: nrf
      repo-path: sdk-nrf
      path: nrf
      revision: v2.4.0-rc1
      import: true
    - name: aws-iot-core-for-sidewalk
      remote: aws-samples
      repo-path: aws-iot-core-for-amazon-sidewalk-sample-app
      path: tools/aws-iot-core-for-sidewalk
      revision: d3f8bded6018901ef99b3d9c5f2c97227f79bb4c


  # West-related configuration for the sidewalk repository.
  self:
    # This repository should be cloned to ncs/sidewalk.
    path: sidewalk
