# The west manifest file (west.yml) for Sidewalk in nRF Connect SDK (NCS).

manifest:
  defaults:
    remote: ncs

  remotes:
    # nRF Connect SDK base URL.
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: nordic-internal
      url-base: ssh://git@bitbucket.nordicsemi.no:7999/ec

  projects:
    - name: nrf
      repo-path: sdk-nrf
      path: nrf
      revision: main
      import: true
    - name: sidewalklib
      repo-path: nrf5-for-sidewalk
      path: sidewalklib
      revision: ncs-libs
      remote: nordic-internal

  # West-related configuration for the sidewalk repository.
  self:
    # This repository should be cloned to ncs/sidewalk.
    path: sidewalk
