# Copyright (c) 2026 Nordic Semiconductor ASA
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

"""Script to generate hardware map used by twister based on userdev_conf file or connected DKs."""
import subprocess

import yaml
import argparse
import logging

logging.basicConfig(level=logging.INFO)

pca_to_board = {
    "PCA10156": "nrf54l15dk/nrf54l15/cpuapp",
    "PCA10188": "nrf54lv10dk/nrf54lv10a/cpuapp",
    "PCA10184": "nrf54lm20dk/nrf54lm20a/cpuapp"
}

family_to_pca = {
    "NRF54L15": "PCA10156",
    "NRF54LV10": "PCA10188",
    "NRF54LM20": "PCA10184"
}


def main(hardware_map_path: str, userdev_conf_path: str):
    """
    Generate HW map file for twister.

    :param hardware_map_path: Available HW generated by twister command:
                              --generate-hardware-map hardware-map.yaml --persistent-hardware-map
    :param userdev_conf_path: userdev_conf file describing installed HW or
                              AUTO key to generate hardware-map basis on connected HW
    :return:
    """
    logging.info("Generating hardware map...")
    if userdev_conf_path.upper() != "AUTO":
        with open(userdev_conf_path) as ud_file:
            userdev_conf = yaml.safe_load(ud_file)["devices"]

        for ud_entry in userdev_conf:
            if ud_entry.get("boards", None):
                # remove io_testers. We don't want to run tests on io_testers
                logging.info(f"remove io_tester {ud_entry}")
                userdev_conf.remove(ud_entry)

    with open(hardware_map_path) as hw_file:
        hardware_map = yaml.safe_load(hw_file)
    to_remove = []
    for hw_entry in hardware_map:
        hw_entry["runner"] = "nrfjprog"
        hw_entry["connected"] = True
        segger = hw_entry["id"].lstrip("0")
        matched_pcas = []
        if userdev_conf_path.upper() != "AUTO":
            matched_pcas = [
                ud_entry["pca"]
                for ud_entry in userdev_conf
                if str(ud_entry.get("segger")) == segger and "pca" in ud_entry
            ]
        else:
            # Read out device family
            if segger.startswith("10508"):
                device_version_cmd = [
                    "nrfjprog", "--deviceversion", "--snr", segger, "--family", "nrf54h"]
            else:
                device_version_cmd = ["nrfjprog",
                                      "--deviceversion", "--snr", segger]
            out = subprocess.run(device_version_cmd, capture_output=True)
            family_string = out.stdout.decode("utf-8").split("_")[0]
            logging.info(
                f"{segger=}, {family_string=}, out={out.stdout.decode('utf-8')}")
            matched_pcas = (
                [family_to_pca[family_string]
                 ] if out.returncode == 0 and family_string in family_to_pca else []
            )
        if matched_pcas:
            # recover DK
            if not segger.startswith("10508"):
                logging.debug(
                    "Call nrfutil device recover to check if board is operable.")
                recover = subprocess.run(
                    ["nrfutil", "device", "recover", "--serial-number", segger], capture_output=True)
                if recover.returncode != 0:
                    # it is OK to continue if recovery fail. This DK will not be taken to test
                    logging.warning(
                        f"Not possible to recover {segger} board, remove from available boards.")
                    to_remove.append(hw_entry)
                    continue
            else:
                logging.warning(
                    "Recover on NRF54H family is not supported yet.")

            try:
                hw_entry["platform"] = pca_to_board[matched_pcas[0]]
            except KeyError:
                logging.warning(
                    f"platform not known or not supported {segger}")
                to_remove.append(hw_entry)
                continue
            if "nrf54l15dk/nrf54l15/cpuapp" in hw_entry["platform"]:
                # If nRF54l board, remove only first serial interface
                hw_entry["runner"] = "nrfutil"
                if segger.startswith("1057") and "-if00" in hw_entry["serial"]:
                    to_remove.append(hw_entry)
        else:
            # HW not known or not connected. Mark for removal
            to_remove.append(hw_entry)

    # remove unuseful HW
    for item in to_remove:
        hardware_map.remove(item)

    with open(f"{hardware_map_path}_filled", "w") as hw_file:
        yaml.dump(hardware_map, hw_file)
    logging.info(f"Final hardware_map content: {hardware_map}")
    logging.info("End")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Script to generate hardware map used by twister based on userdev_conf file or connected DKs."
    )

    parser.add_argument(
        "--userdev_conf_path",
        required=True,
        type=str,
        help="'userdev_conf file' describing installed HW or 'AUTO' to generate hardware-map basis on connected HW",
    )
    parser.add_argument(
        "--hardware_map_path",
        required=True,
        type=str,
        help="Available HW generated by twister command: --generate-hardware-map\
             hardware-map.yaml --persistent-hardware-map",
    )
    args = parser.parse_args()

    main(args.hardware_map_path, args.userdev_conf_path)
