
/*
 * Copyright 2024 Amazon.com, Inc. or its affiliates. All rights reserved.
 *
 * AMAZON PROPRIETARY/CONFIDENTIAL
 *
 * You may not use this file except in compliance with the terms and
 * conditions set forth in the accompanying LICENSE.txt file.
 *
 * THESE MATERIALS ARE PROVIDED ON AN "AS IS" BASIS. AMAZON SPECIFICALLY
 * DISCLAIMS, WITH RESPECT TO THESE MATERIALS, ALL WARRANTIES, EXPRESS,
 * IMPLIED, OR STATUTORY, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
 */

#ifndef SID_PROTOCOL_EXT_OPTS_H
#define SID_PROTOCOL_EXT_OPTS_H

#define RNET_LOG_RAW_PKT 0
#define SYSTEM_RST_REPORTS 0
#define DFU_SETTINGS_ENABLED 0

#if WAN_SUPPORT
#define SID_MAC_LDR_ENABLED 1
#define HALO_GCS_DISABLE_P2P 1
#define SID_LINK2_PROFILE_2_SUPPORT 1
#endif

#endif