#!/bin/sh

# Copyright (c) 2022 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

#  Run unit tests and tests on native_sim. Tests for nrf54l15dk/nrf54l15/cpuapp are only build.
#  This script takes very long time, so it is not enabled by default ( first run ~15min, cachced builds ~5min)
#  To enable this hook create symbolic link to sidewalk/.git/hook/pre-push

SIDEWALK_PATH=$(git rev-parse --show-toplevel)
TWISTER_BIN=$SIDEWALK_PATH/../zephyr/scripts/twister

$TWISTER_BIN -p native_sim -p unit_testing -p nrf54l15dk/nrf54l15/cpuapp -n --enable-asan --enable-lsan --clobber-output -T $SIDEWALK_PATH --tag Sidewalk
