#!/bin/sh
UNCRUST_CONFIG="$ZEPHYR_BASE/../sidewalk/.uncrustify.cfg"
# get list of staged files
staged_files=$(git diff --name-only --staged --diff-filter=AMR | grep -E '\.(c|h|cpp|hpp)$')
if [ -n "$staged_files" ]; then
    non_mamazon_files=$(grep -l -L "Copyright .* Amazon.com, Inc. or its affiliates. All rights reserved." $staged_files)
    if [ -n "$non_mamazon_files" ]; then

        echo "## Executing uncrustify"
        uncrustify -c $UNCRUST_CONFIG --check $non_mamazon_files 
        if [ $? -ne 0 ]; then
            uncrustify -c $UNCRUST_CONFIG --replace --no-backup $staged_files 
            echo "suggested changes were made on the tracked files, please review them and stage for commit"
            exit 1
        fi
    fi
fi
