/*
 * Copyright 2018-2020 Amazon.com, Inc. or its affiliates. All rights reserved.
 *
 * AMAZON PROPRIETARY/CONFIDENTIAL
 *
 * You may not use this file except in compliance with the terms and
 * conditions set forth in the accompanying LICENSE.txt file.
 *
 * THESE MATERIALS ARE PROVIDED ON AN "AS IS" BASIS. AMAZON SPECIFICALLY
 * DISCLAIMS, WITH RESPECT TO THESE MATERIALS, ALL WARRANTIES, EXPRESS,
 * IMPLIED, OR STATUTORY, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
 */

#ifndef STORAGE_KV_KEYS_H
#define STORAGE_KV_KEYS_H

#ifdef __cplusplus
extern "C" {
#endif

// Note per:
// http://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v14.2.0%2Flib_fds_functionality.html&cp=4_0_0_3_50_1_4&anchor=lib_fds_functionality_keys
// Record keys need to be in the range 0x0001-0xBFFF

// FDS key IDs used for storing RingNet configuration records in an FDS file
typedef enum {
    STORAGE_KV_VERSION = 1,
    STORAGE_KV_PEERING_CHANNEL,
    STORAGE_KV_PAN_ID,
    STORAGE_KV_P2P_BROADCAST_KEY,
    STORAGE_KV_P2P_UNICAST_KEY,
    STORAGE_KV_DBG_DEV_ID,
    STORAGE_KV_UNCONFIRMED_MULTICAST_RETRIES,
    STORAGE_KV_GROUP_NUM,
    STORAGE_KV_SEC_BLE_CONTEXT_KEY,     //GCMKEY(16B)+PeerNonce(8B)+Counter(6B)
    STORAGE_KV_SEC_CLOUD_CONTEXT_KEY,   //GCMKEY(16B)+PeerNonce(8B)+Counter(6B)
    STORAGE_KV_PAIRING_STATE_KEY,
    STORAGE_KV_KA_INTERVAL,
    STORAGE_KV_REJOIN_PARAMS,
    STORAGE_KV_DFU_PARAMS,
    STORAGE_KV_CAD_PARAMS,
    STORAGE_KV_RF_SECURITY_SETTINGS,
    STORAGE_KV_SLEEPY_DEVICE_PARAMS,
    STORAGE_KV_PROTOCOL_SWITCH,
    STORAGE_KV_MAX_BCN_MISS,
    STORAGE_KV_BCN_INTERVAL_FACTOR,
    STORAGE_KV_LDR_CHANNEL,
    STORAGE_KV_INTERNAL_MAC_SWITCH,
    STORAGE_KV_DEV_VERSION,
    STORAGE_KV_NG_DISCOVERY_PARAMS,
    STORAGE_KV_HOMEPAN_SCAN_INTVL,
    STORAGE_KV_PROTOCOL_VERSION,
    STORAGE_KV_SIDEWALK_NW_FLAG,
    STORAGE_KV_WAN_MASTER_KEY,
    STORAGE_KV_WAN_KEY_PARAMS,
    STORAGE_KV_APP_MASTER_KEY,
    STORAGE_KV_APP_KEY_PARAMS,
    STORAGE_KV_TSYNC_COUNTER_SEED,
    STORAGE_KV_TSYNC_COUNTER,
    STORAGE_KV_TX_UUID_PARAMS,
    STORAGE_KV_RF_POWER_LORA,
    STORAGE_KV_RF_POWER_FSK,
    STORAGE_KV_HDR_PRDCTY_INFO,
    STORAGE_KV_HDR_OFFSET_INFO,
    STORAGE_KV_CONFIGURATION_COMPLETE,
    STORAGE_KV_LAST_OPERATING_GW_MODE,
    STORAGE_KV_DISTRESS_GWD_PARAMS,
    STORAGE_KV_TMP_PRTCL_EXP, /* record for temporary protocol configuration needs */
    STORAGE_KV_SIDEWALK_ID,
    STORAGE_KV_HDR_WAKEUP_INFO,
    STORAGE_KV_RF_POWER,
    STORAGE_KV_DEVICE_CLASS_FSK,
    STORAGE_KV_DEVICE_CLASS_LDR,
    STORAGE_KV_D2D_MASTER_KEY,
    STORAGE_KV_D2D_KEY_PARAMS,
    STORAGE_KV_LAST_ENTRY
} storage_kv_key_t;

#ifdef __cplusplus
}
#endif

#endif
