/*
 * Copyright 2019-2024 Amazon.com, Inc. or its affiliates. All rights reserved.
 *
 * AMAZON PROPRIETARY/CONFIDENTIAL
 *
 * You may not use this file except in compliance with the terms and
 * conditions set forth in the accompanying LICENSE.TXT file.
 *
 * THESE MATERIALS ARE PROVIDED ON AN "AS IS" BASIS. AMAZON SPECIFICALLY
 * DISCLAIMS, WITH RESPECT TO THESE MATERIALS, ALL WARRANTIES, EXPRESS,
 * IMPLIED, OR STATUTORY, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
 */
/*
 *
 */

#ifndef _ACE_CONFIG_H_
#define _ACE_CONFIG_H_

#define PACKAGE_BUILD
#define RTOS_PACKAGE
#define INSTALL_PACKAGE
#define INSTALL_PATH "../installed_ace"
#define BUILD_TEST_CODE
#define INCLUDE_HAL_HEADERS
#define HAL_UNIT_TESTS
#define HAL_UNIT_TESTS_KV_STORAGE
#define HAL_UNIT_TESTS_DHA
#define HAL_UNIT_TESTS_IDME
#define HAL_UNIT_TESTS_DEVICE_INFO
#define HAL_UNIT_TESTS_LED
#define HAL_UNIT_TESTS_BUTTON
#define HAL_UNIT_TESTS_IDT
#define OSAL_DEFAULT_LOG_LEVEL 1
#define OSAL_FREERTOS
#define ACE_API_TEST
#define ACE_API_TEST_THREAD
#define ACE_API_TEST_SEMAPHORE
#define ACE_API_TEST_SOCKET
#define ACE_API_TEST_MUTEX
#define ACE_API_TEST_MESSAGE_QUEUE
#define ACE_API_TEST_SHMEM
#define ACE_API_TEST_TIME
#define ACE_API_TEST_FILES
#define ACE_API_TEST_FILE_NAME "/tmp/test.txt"
#define ACE_DISPATCHER_LIB
#define ACE_LOG
#define ACE_CLI
#define ACE_EVENTS_LIB
#define MW_DROPBOX
#define ACE_PERF_INSTRUMENT
#define AFR_BDTOOL_CLI
#define TLSCONFIG
#define ACE_MAPLITE_MIDDLEWARE
#define ACE_MAPLITE_ASYNC
#define ACE_MAPLITE_UTILITY
#define ACE_FFS_PROVISIONABLE_MIDDLEWARE
#define ACE_FFS_PROVISIONABLE_TEST_CLI
#define ACE_FACTORYRESET_MIDDLEWARE
#define ACE_FACTORYRESET_ASYNC_MAPLITE
#define ACE_DEVICE_INFO
#define ACE_DEVICE_INFO_TEST
#define ACE_WIFI_MIDDLEWARE
#define ACE_WIFI_MAX_SCAN_RESULTS 20
#define ACE_WIFI_MAX_CONFIGURED_NETWORKS 2
#define ACE_WIFI_RTOS
#define ACE_WIFI_MAX_NUM_CB 5
#define ACE_CONNECTIVITY_MANAGER
#define ACE_BT_MIDDLEWARE
#define ACE_BT_CLASSIC_PROFILES_SUPPORT n
#define ACE_BT_BLE_SUPPORT
#define ACE_BT_LITE_SUPPORT
#define ACE_METRIC_API
#define METRIC_MODE_THREAD
#define METRIC_ENABLE_METRIC_MGR
#define METRIC_TRANSPORT_USE_ACM
#define HTTP_PARSER_LIB
#define CJSON_LIB
#define NANOPB_LIB
#define LIBWEBSOCKETS_LIB
#define LIBWEBSOCKETS_WITHOUT_H2
#define ACE_UNWIND_WRAPPER
#define ACE_MALLOC_WRAPPER
#define ACE_STACK_CANARY
#define ACE_HEAP_GUARD
#define ACE_HEAP_TRACK
#define ACE_TOOLS_DEBUG
#define ACE_SYS_TOOLBOX
#define ACE_KVS_DS_DEFAULT_GROUP "deviceData"
#define ACE_MAPLITE_DS_GROUP "map"
#define ACE_NET_DS_GROUP "WifiCred"
#define NATIVE_DEVICE_OTA_LIB
#define ACE_OTA_MIDDLEWARE
#define ACE_OTA_USE_ACM
#define ACE_OTA_DOWNLOADER
#define ACE_OTA_MIDDLEWARE_TEST
#define JSMN_LIB
#define LC
#define LC_DISPATCHERS "beignetd"
#define LC_BEIGNETD_STACK 8192
#define LC_BEIGNETD_PRIORITY 5
#define LC_BEIGNETD_QUEUESIZE 20
#define LC_BEIGNETD_MODULES "ace_ota_daemon, ace_ota_downloader, ace_logmgr, metric_mgr, ace_maplite_daemon_disp"
#define LC_BEIGNETD_AUTOSTART

#endif /*_ACE_CONFIG_H_*/
