/*
 * Copyright 2020 Amazon.com, Inc. or its affiliates. All rights reserved.
 *
 * AMAZON PROPRIETARY/CONFIDENTIAL
 *
 * You may not use this file except in compliance with the terms and
 * conditions set forth in the accompanying LICENSE.txt file.
 *
 * THESE MATERIALS ARE PROVIDED ON AN "AS IS" BASIS. AMAZON SPECIFICALLY
 * DISCLAIMS, WITH RESPECT TO THESE MATERIALS, ALL WARRANTIES, EXPRESS,
 * IMPLIED, OR STATUTORY, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
 */

#ifndef SID_PAL_MFG_STORE_OFFSETS_H
#define SID_PAL_MFG_STORE_OFFSETS_H

#include <sid_pal_mfg_store_ifc.h>

#include <assert.h>

/* This enumeration stores 4-byte word offset constants for the contents of the
 * manufacturing store. Each value will consume the smallest number of 4-byte
 * words capable of storing the value based on on the value size.
 *
 * Take care when adding new values to maintain backward compatibility.
 */

#define WORD_SIZE 4
#define WORD_OFFSET(prev_offset, prev_size) (prev_offset + (prev_size + WORD_SIZE -1)/WORD_SIZE)

#if SID_PAL_MFG_STORE_NORDIC_USE_LEGACY_OFFSETS

enum {
    SID_PAL_MFG_STORE_OFFSET_VERSION                          = 0,
    SID_PAL_MFG_STORE_OFFSET_DEVID                            = 4,
    SID_PAL_MFG_STORE_OFFSET_SERIAL_NUM                       = 32,
    SID_PAL_MFG_STORE_OFFSET_APP_PUB_ED25519                  = 92,
    SID_PAL_MFG_STORE_OFFSET_DEVICE_PRIV_ED25519              = 100,
    SID_PAL_MFG_STORE_OFFSET_DEVICE_PUB_ED25519               = 108,
    SID_PAL_MFG_STORE_OFFSET_DEVICE_PUB_ED25519_SIGNATURE     = 116,
    SID_PAL_MFG_STORE_OFFSET_DEVICE_PRIV_P256R1               = 132,
    SID_PAL_MFG_STORE_OFFSET_DEVICE_PUB_P256R1                = 140,
    SID_PAL_MFG_STORE_OFFSET_DEVICE_PUB_P256R1_SIGNATURE      = 156,
    SID_PAL_MFG_STORE_OFFSET_PRODUCT_PUB_ED25519              = 172,
    SID_PAL_MFG_STORE_OFFSET_PRODUCT_PUB_ED25519_SIGNATURE    = 180,
    SID_PAL_MFG_STORE_OFFSET_PRODUCT_ED25519_SERIAL           = 196,
    SID_PAL_MFG_STORE_OFFSET_PRODUCT_PUB_P256R1               = 197,
    SID_PAL_MFG_STORE_OFFSET_PRODUCT_PUB_P256R1_SIGNATURE     = 213,
    SID_PAL_MFG_STORE_OFFSET_PRODUCT_P256R1_SERIAL            = 229,
    SID_PAL_MFG_STORE_OFFSET_MAN_PUB_ED25519                  = 230,
    SID_PAL_MFG_STORE_OFFSET_MAN_PUB_ED25519_SIGNATURE        = 238,
    SID_PAL_MFG_STORE_OFFSET_MAN_ED25519_SERIAL               = 254,
    SID_PAL_MFG_STORE_OFFSET_MAN_PUB_P256R1                   = 255,
    SID_PAL_MFG_STORE_OFFSET_MAN_PUB_P256R1_SIGNATURE         = 271,
    SID_PAL_MFG_STORE_OFFSET_MAN_P256R1_SERIAL                = 287,
    SID_PAL_MFG_STORE_OFFSET_AMZN_PUB_ED25519                 = 352,
    SID_PAL_MFG_STORE_OFFSET_AMZN_PUB_P256R1                  = 360,
    SID_PAL_MFG_STORE_OFFSET_APID                             = 576,

    SID_PAL_MFG_STORE_OFFSET_SMSN                             = SID_PAL_MFG_STORE_INVALID_OFFSET,
    SID_PAL_MFG_STORE_OFFSET_DAK_PUB_ED25519                  = SID_PAL_MFG_STORE_INVALID_OFFSET,
    SID_PAL_MFG_STORE_OFFSET_DAK_PUB_ED25519_SIGNATURE        = SID_PAL_MFG_STORE_INVALID_OFFSET,
    SID_PAL_MFG_STORE_OFFSET_DAK_ED25519_SERIAL               = SID_PAL_MFG_STORE_INVALID_OFFSET,
    SID_PAL_MFG_STORE_OFFSET_DAK_PUB_P256R1                   = SID_PAL_MFG_STORE_INVALID_OFFSET,
    SID_PAL_MFG_STORE_OFFSET_DAK_PUB_P256R1_SIGNATURE         = SID_PAL_MFG_STORE_INVALID_OFFSET,
    SID_PAL_MFG_STORE_OFFSET_DAK_P256R1_SERIAL                = SID_PAL_MFG_STORE_INVALID_OFFSET,
    SID_PAL_MFG_STORE_OFFSET_SW_PUB_ED25519                   = SID_PAL_MFG_STORE_INVALID_OFFSET,
    SID_PAL_MFG_STORE_OFFSET_SW_PUB_ED25519_SIGNATURE         = SID_PAL_MFG_STORE_INVALID_OFFSET,
    SID_PAL_MFG_STORE_OFFSET_SW_ED25519_SERIAL                = SID_PAL_MFG_STORE_INVALID_OFFSET,
    SID_PAL_MFG_STORE_OFFSET_SW_PUB_P256R1                    = SID_PAL_MFG_STORE_INVALID_OFFSET,
    SID_PAL_MFG_STORE_OFFSET_SW_PUB_P256R1_SIGNATURE          = SID_PAL_MFG_STORE_INVALID_OFFSET,
    SID_PAL_MFG_STORE_OFFSET_SW_P256R1_SERIAL                 = SID_PAL_MFG_STORE_INVALID_OFFSET,
};

#else
/*
 * Common values for Sidewalk for Sidewalk/BLE support
 * These are 4-byte word offsets.
 */
/*
 * Magic number format (little-endian)
 * bytes 0-2 = 'S' 'I' 'D', byte 3 = version
 */
enum {
    SID_PAL_MFG_STORE_OFFSET_MAGIC                          = 0,
    SID_PAL_MFG_STORE_OFFSET_VERSION                        = 1,
    SID_PAL_MFG_STORE_OFFSET_SERIAL_NUM                     = 2,
    SID_PAL_MFG_STORE_OFFSET_SMSN                           = 8,
    SID_PAL_MFG_STORE_OFFSET_APID                           = 16,
    SID_PAL_MFG_STORE_OFFSET_APP_PUB_ED25519                = 18,
    SID_PAL_MFG_STORE_OFFSET_DEVICE_PRIV_ED25519            = 26,
    SID_PAL_MFG_STORE_OFFSET_DEVICE_PUB_ED25519             = 34,
    SID_PAL_MFG_STORE_OFFSET_DEVICE_PUB_ED25519_SIGNATURE   = 42,
    SID_PAL_MFG_STORE_OFFSET_DEVICE_PRIV_P256R1             = 58,
    SID_PAL_MFG_STORE_OFFSET_DEVICE_PUB_P256R1              = 66,
    SID_PAL_MFG_STORE_OFFSET_DEVICE_PUB_P256R1_SIGNATURE    = 82,
    SID_PAL_MFG_STORE_OFFSET_DAK_PUB_ED25519                = 98,
    SID_PAL_MFG_STORE_OFFSET_DAK_PUB_ED25519_SIGNATURE      = 106,
    SID_PAL_MFG_STORE_OFFSET_DAK_ED25519_SERIAL             = 122,
    SID_PAL_MFG_STORE_OFFSET_DAK_PUB_P256R1                 = 123,
    SID_PAL_MFG_STORE_OFFSET_DAK_PUB_P256R1_SIGNATURE       = 139,
    SID_PAL_MFG_STORE_OFFSET_DAK_P256R1_SERIAL              = 155,
    SID_PAL_MFG_STORE_OFFSET_PRODUCT_PUB_ED25519            = 156,
    SID_PAL_MFG_STORE_OFFSET_PRODUCT_PUB_ED25519_SIGNATURE  = 164,
    SID_PAL_MFG_STORE_OFFSET_PRODUCT_ED25519_SERIAL         = 180,
    SID_PAL_MFG_STORE_OFFSET_PRODUCT_PUB_P256R1             = 181,
    SID_PAL_MFG_STORE_OFFSET_PRODUCT_PUB_P256R1_SIGNATURE   = 197,
    SID_PAL_MFG_STORE_OFFSET_PRODUCT_P256R1_SERIAL          = 213,
    SID_PAL_MFG_STORE_OFFSET_MAN_PUB_ED25519                = 214,
    SID_PAL_MFG_STORE_OFFSET_MAN_PUB_ED25519_SIGNATURE      = 222,
    SID_PAL_MFG_STORE_OFFSET_MAN_ED25519_SERIAL             = 238,
    SID_PAL_MFG_STORE_OFFSET_MAN_PUB_P256R1                 = 239,
    SID_PAL_MFG_STORE_OFFSET_MAN_PUB_P256R1_SIGNATURE       = 255,
    SID_PAL_MFG_STORE_OFFSET_MAN_P256R1_SERIAL              = 271,
    SID_PAL_MFG_STORE_OFFSET_SW_PUB_ED25519                 = 272,
    SID_PAL_MFG_STORE_OFFSET_SW_PUB_ED25519_SIGNATURE       = 280,
    SID_PAL_MFG_STORE_OFFSET_SW_ED25519_SERIAL              = 296,
    SID_PAL_MFG_STORE_OFFSET_SW_PUB_P256R1                  = 297,
    SID_PAL_MFG_STORE_OFFSET_SW_PUB_P256R1_SIGNATURE        = 313,
    SID_PAL_MFG_STORE_OFFSET_SW_P256R1_SERIAL               = 329,
    SID_PAL_MFG_STORE_OFFSET_AMZN_PUB_ED25519               = 330,
    SID_PAL_MFG_STORE_OFFSET_AMZN_PUB_P256R1                = 338,
    SID_PAL_MFG_STORE_SID_V0_MAX_OFFSET                     = 346,

    SID_PAL_MFG_STORE_OFFSET_DEVID                          = SID_PAL_MFG_STORE_INVALID_OFFSET,
};

#endif

#endif
