#
# Copyright (c) 2024 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_MAIN_STACK_SIZE=10240

CONFIG_BOOT_BOOTSTRAP=n
CONFIG_PM=n

CONFIG_FLASH=y
CONFIG_FPROTECT=y

CONFIG_BOOT_MAX_IMG_SECTORS=256

# Software-based downgrade prevention (requires MCUBOOT_MODE_OVERWRITE_ONLY in sysbuild)
CONFIG_MCUBOOT_DOWNGRADE_PREVENTION=y

# Use picolibc to reduce flash usage
CONFIG_PICOLIBC=y
CONFIG_CBPRINTF_NANO=y
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=0

# Disable logs
CONFIG_BOOT_BANNER=n
CONFIG_NCS_BOOT_BANNER=n
CONFIG_SERIAL=n
CONFIG_LOG=n
CONFIG_LOG_MODE_MINIMAL=n
CONFIG_PRINTK=n
CONFIG_ASSERT=n

# Bootloader size optimization
CONFIG_CONSOLE=n
CONFIG_CONSOLE_HANDLER=n
CONFIG_UART_CONSOLE=n
CONFIG_USE_SEGGER_RTT=n
CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_GPIO=n
CONFIG_TIMESLICING=n
CONFIG_MULTITHREADING=n
CONFIG_TICKLESS_KERNEL=n
CONFIG_TIMEOUT_64BIT=n
CONFIG_NRF_ENABLE_ICACHE=n
CONFIG_SIZE_OPTIMIZATIONS=y

# Activate LTO
CONFIG_LTO=y
CONFIG_ISR_TABLES_LOCAL_DECLARATION=y
