name: NRF upmerge

on:
  schedule:
    - cron: "0 1 * * 0"
  
  workflow_dispatch:

jobs:
  Change_NRF_revision:

    name: Create PR with NRF upmerge
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - name: Checkout sidewalk
        uses: actions/checkout@v3
        with:
          path: sidewalk
          ref: main
      
      - name: Checkout nrf
        uses: actions/checkout@v3
        with:
          repository: nrfconnect/sdk-nrf
          path: nrf
          ref: main

      - name: Change nrf revision
        run: |
          nrf_hash="$(git -C nrf rev-parse HEAD)"
          python3 sidewalk/scripts/ci/replace_nrf_revision_in_west.py -r $nrf_hash sidewalk/west.yml 
      - name: Get Date
        id: date
        run: |
          echo "date=$(date +%Y_%d_%m)" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{secrets.NCS_GITHUB_TOKEN}}
          path: sidewalk
          commit-message: "NRF: upmerge\n\nupdate nrf revision in west.yml"
          title: "NRF upmerge ${{steps.date.outputs.date}}"
          body: "PR created automatically by GitHub actions to change revision of NRF in west.yml"
          delete-branch: true
          branch: nrf_upmerge-${{steps.date.outputs.date}}
          signoff: true
