name: Build documentation on PR

on:
  pull_request:
    paths:
      - '**/doc/**'
      - '**/*.rst'

concurrency:
  group: docs-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build_documentation:
    uses: ./.github/workflows/documentation_build.yml
    with:
      documentation_tag: pr-${{ github.event.pull_request.number }}
