name: On PR action
on:
  pull_request:
    branches:
      - main

jobs:
  ValidateCodeCompliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          python3 -m pip install -r ./scripts/ci/requirements.txt && sudo apt install uncrustify

      - name: Check formatting
        run: |
          python3 ./scripts/ci/verify_formatting.py -d -s . -c ./scripts/ci/formatter_cfg.yml

      - name: Check license
        run: |
          python3 ./scripts/ci/verify_license.py -s . -c ./scripts/ci/license.yml

  Build_samples:
    needs: ValidateCodeCompliance
    strategy:
      matrix:
        samples_to_test:
          - template_subghz
          - template_ble
          - sensor_monitoring
          - sid_dut

    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:main
      options: --cpus 2

    steps:          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Reconfigure west
        run: |
          cp -r ../sdk-sidewalk /workdir/sidewalk
          cd /workdir
          west config manifest.path sidewalk
          west update -n -o=--depth=1

      - name: twister build samples 
        run: /workdir/zephyr/scripts/twister --testsuite-root /workdir/sidewalk/samples/${{ matrix.samples_to_test }} --no-clean --show-footprint --footprint-from-buildlog -vvv --build-only
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sample-${{ matrix.samples_to_test }}
          path: |
            twister-out/**/sidewalk/samples/**/*sidewalk*/zephyr/zephyr.elf
            twister-out/**/sidewalk/samples/**/*sidewalk*/zephyr/zephyr.hex
            twister-out/**/sidewalk/samples/**/*sidewalk*/zephyr/dfu_application.zip
            twister-out/**/sidewalk/samples/**/*sidewalk*/zephyr/.config
            twister-out/twister.json

  Run_Unit_Tests: 
    needs: ValidateCodeCompliance
    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:main
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Reconfigure west
        run: |
          cp -r ../sdk-sidewalk /workdir/sidewalk
          cd /workdir
          west config manifest.path sidewalk
          west update -n -o=--depth=1

      - name: twister build and run x86 tests 
        run: /workdir/zephyr/scripts/twister --testsuite-root /workdir/sidewalk/tests/unit_tests --no-clean -vvv

  Build_manual_tests:
    needs: ValidateCodeCompliance
    strategy:
      matrix:
        samples_to_test:
          - functional
          - manual
          - validation
    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:main
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Reconfigure west
        run: |
          cp -r ../sdk-sidewalk /workdir/sidewalk
          cd /workdir
          west config manifest.path sidewalk
          west update -n -o=--depth=1

      - name: twister build and run x86 tests 
        run: /workdir/zephyr/scripts/twister --testsuite-root /workdir/sidewalk/tests/${{ matrix.samples_to_test }} --no-clean -vvv
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tests-${{ matrix.samples_to_test }} 
          path: |
            twister-out/**/sidewalk/samples/**/*sidewalk*/zephyr/zephyr.elf
            twister-out/**/sidewalk/samples/**/*sidewalk*/zephyr/zephyr.hex
            twister-out/**/sidewalk/samples/**/*sidewalk*/zephyr/dfu_application.zip
            twister-out/**/sidewalk/samples/**/*sidewalk*/zephyr/.config
            twister-out/twister.json

  Create_comment_with_memory_usage:
    needs: Build_samples
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get artifacts from current build
        uses: actions/download-artifact@v3
        with:
          path: current

      - name: Get artifacts from base build
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: on_commit.yml
          commit: ${{github.event.pull_request.base.sha}}
          path: old
          if_no_artifact_found: warn
      
      - name: Generage memory diff
        run: |
          python3 scripts/ci/combine_twister_reports.py current/sample-template_subghz/twister.json current/sample-template_ble/twister.json current/sample-sensor_monitoring/twister.json current/sample-sid_dut/twister.json new.json
          echo "{}" > old.json
          python3 scripts/ci/combine_twister_reports.py old/sample-template_subghz/twister.json old/sample-template_ble/twister.json old/sample-sensor_monitoring/twister.json old/sample-sid_dut/twister.json old.json
          python3 scripts/ci/compare_size_reports.py -o old.json -n new.json --md_output --show_only_diff > memory_usage.md
          echo ${{ github.event.number }} > pr_number
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PR_comment
          path: |
            memory_usage.md
            pr_number
     
