name: Publish documentation

on:
  workflow_dispatch:
    inputs:
      documentation_tag:
        type: string
        required: false
        default: "latest"
        description: "Label of the documentation"
      publish_to_prod:
        type: boolean
        default: true
      publish_to_dev:
        type: boolean
        default: true

  workflow_call:
    inputs:
      documentation_tag:
        type: string
        required: true
        default: "latest"
      publish_to_prod:
        type: boolean
        default: true
      publish_to_dev:
        type: boolean
        default: true

jobs:
  build:
    uses: ./.github/workflows/documentation_build.yml
    with:
      documentation_tag: ${{ inputs.documentation_tag }}

  publish:
    name: Publish documentation to Zoomin
    needs: build
    if: inputs.publish_to_dev || inputs.publish_to_prod
    runs-on: ubuntu-24.04
    env:
      ARCHIVE: "addon-sidewalk_${{ inputs.documentation_tag }}.zip"

    steps:
      - name: Download documentation archive
        uses: actions/download-artifact@v4
        with:
          name: documentation

      - name: Prepare Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ vars.NCS_ZOOMIN_SERVER }} >> ~/.ssh/known_hosts
          echo "${{ secrets.NCS_ZOOMIN_KEY }}" > zoomin_key
          chmod 600 zoomin_key

      - name: Publish documentation - dev
        if: inputs.publish_to_dev
        run: |
          sftp -v -i zoomin_key ${{ vars.NCS_ZOOMIN_USER }}@${{ vars.NCS_ZOOMIN_SERVER }} <<EOF
            cd ${{ vars.NCS_ZOOMIN_DEPLOY_DEV_PATH }}
            put ${{ env.ARCHIVE }}
          EOF

      - name: Publish documentation - prod
        if: inputs.publish_to_prod
        run: |
          sftp -v -i zoomin_key ${{ vars.NCS_ZOOMIN_USER }}@${{ vars.NCS_ZOOMIN_SERVER }} <<EOF
            cd ${{ vars.NCS_ZOOMIN_DEPLOY_PROD_PATH }}
            put ${{ env.ARCHIVE }}
          EOF
