name: Build Sidewalk samples
on:
  workflow_call:
    inputs:
      jobs_per_subset:
        type: number
        required: false
        default: 4
      save_images:
        type: boolean
        required: false
        default: true


jobs:
  discover_targets:
    runs-on: self-hosted
    container:
      image: ghcr.io/nrfconnect/sdk-sidewalk:main
      options: --cpus 2 --privileged
    outputs:
      total_platforms_json: ${{ steps.subsets.outputs.total_platforms_json }}
      subset_matrix: ${{ steps.subsets.outputs.matrix }}
      subset_config: ${{ steps.subsets.outputs.config }}
    defaults:
      run:
        shell: nrfutil toolchain-manager launch --install-dir /root/ncs bash -- {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: sidewalk

      - name: update NRF
        run: |
          rm -rf .west;
          west init -l sidewalk --mf west.yml &&
          west update -n -o=--depth=1 --path-cache /workdir/

      - name: subsets configuration
        id: subsets
        run: |
          rm -rf twister-out* max max_sorted configuration
          west twister --test-config sidewalk/test_config.yaml --testsuite-root sidewalk --level="samples" --dry-run
          total_platforms=$(jq -r '.testsuites |map({platform: .platform}) | unique | .[].platform' twister-out/testplan.json)
          total_platforms_json=$(printf '%s' "${total_platforms[@]}" | jq -R . | jq -s -c .)
          echo "{}" > configuration
          for platform in $total_platforms; do
            west twister --test-config sidewalk/test_config.yaml --testsuite-root sidewalk --level="samples" --dry-run --platform $platform
            total_jobs=$(jq '.testsuites | length' twister-out/testplan.json)
            subsets=$(( ( total_jobs + ${{inputs.jobs_per_subset}}) / ${{inputs.jobs_per_subset}}))
            echo $subsets >> max
            cat configuration | jq -c --arg platform_name $platform --arg subsets $subsets '. += {($platform_name): $subsets|tonumber }' > configuration_new
            mv configuration_new configuration
          done
          sort max > max_sorted
          max_subset=$(tail -n 1 max_sorted)
          subset_matrix="[$(seq -s ', ' 1 $max_subset)]"
          cat configuration
          echo $subset_matrix

          echo "total_platforms_json=$total_platforms_json" >> $GITHUB_OUTPUT;
          echo "matrix=$subset_matrix" >> $GITHUB_OUTPUT;
          echo "config=`cat configuration`" >> $GITHUB_OUTPUT;

      - name: clean
        if: always()
        run: |
          rm -rf twister* sidewalk* max max_sorted configuration

  build_samples:
    needs: [discover_targets]
    strategy:
      fail-fast: false
      matrix:
        subset: ${{ fromJson(needs.discover_targets.outputs.subset_matrix) }}
        target: ${{ fromJson(needs.discover_targets.outputs.total_platforms_json) }}

    uses: ./.github/workflows/samples_build_target.yml
    with:
      target: ${{matrix.target}}
      subset: ${{matrix.subset}}
      subset_config: '${{needs.discover_targets.outputs.subset_config}}'

  merge_sample_artifacts:
    needs: build_samples
    runs-on: ubuntu-24.04
    permissions: write-all
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          delete-merged: true
          name: sample-artifacts-meta
          pattern: sample-artifacts-meta-*
          include-hidden-files: true

      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        if: ${{ inputs.save_images }}
        with:
          delete-merged: true
          name: sample-artifacts
          pattern: sample-artifacts-build-*
          include-hidden-files: true
